Pranay Code Review
uwdb/lightdb pull request #26
Opened 2020-04-05 18:21 UTC by mundrapranay

Removed build directory. Code review for merge.

2020-04-06 03:59 UTC, BrandonHaynes requested changes

2020-04-06 03:59 UTC, BrandonHaynes commented on CMakeLists.txt
> +message("FFmpeg include: ${FFMPEG_INCLUDE_DIRS}")
Can remove `message` directives

2020-04-06 03:59 UTC, BrandonHaynes commented on CMakeLists.txt
> +add_subdirectory(python EXCLUDE_FROM_ALL)
Is `EXCLUDE_FROM_ALL` correct here?

2020-04-06 03:59 UTC, BrandonHaynes commented on cmake/Modules/FindGPAC.cmake
> +  set(GPAC_LIBRARIES "/usr/lib/x86_64-linux-gnu/libgpac.so")
Why the hardcoded path?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/CMakeLists.txt
> +  if (subdir MATCHES "../python/src")
Can we use a glob that excludes `python/src` instead of doing a `foreach`?  Why are we excluding, anyway?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/catalog/src/Catalog.cc
> +#include <iostream>
Why are we adding `iostream`?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/model/include/Algebra.h
> +        bool Check();
?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +    public:
Should this be part of the base class?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +        static constexpr const Volume angular() { return {{0, 0}, {0, 0}, {0, 0}, {0, 0},
What does `angular` mean?

2020-04-06 03:59 UTC, BrandonHaynes commented on core/model/src/Algebra.cc
> +    bool Check() { return true; }
?

2020-04-06 03:59 UTC, BrandonHaynes commented on plugins/blur/tmp/blur-cfgcmd.txt
> +cmd='/usr/local/bin/cmake;-DCMAKE_BUILD_TYPE=debug;-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>;-DLIGHTDB_INCLUDES:list=/home/pranay99/lightdb/thirdparty/NvEnc/inc|/usr/local/cuda-9.0/include|/usr/inclu
?

2020-04-06 03:59 UTC, BrandonHaynes commented on plugins/blur/tmp/blur-cfgcmd.txt.in
> +cmd='@cmd@'
?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/CMakeLists.txt
> +#set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/../cmake/Modules/")
Deal with/remove commented code

2020-04-06 03:59 UTC, BrandonHaynes commented on python/CMakeLists.txt
> +set(ALGEBRA_SOURCES "src/Algebra_ext.cc")
Avoid hardcoded files

2020-04-06 03:59 UTC, BrandonHaynes commented on python/CMakeLists.txt
> +message("boost libraries: ${Boost_LIBRARIES}")
Remove extraneous messages, unless needed

2020-04-06 03:59 UTC, BrandonHaynes commented on test/src/execution/SelectionTests.cc
> +TEST_F(SelectionTestFixture, testPythonQuery) {
Python tests should be in their own directory

2020-04-06 03:59 UTC, BrandonHaynes commented on test/src/execution/UDFTests.cc
> +                    .Save("/home/maureen/grey_test.hevc");
No hardcoded paths

2020-04-06 03:59 UTC, BrandonHaynes commented on test/src/planning/VisitorTests.cc
> +    auto yolo = lightdb::extensibility::Load("yolo");//, "/home/maureen/lightdb/plugins/yolo/cmake-build-debug/");
Hardcoded paths

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +#include <boost/python.hpp>
Dependencies before local includes

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +namespace Python {
`LightDB::Python`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +class PythonLightField {
Move to `PythonLightField.h`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        return PythonLightField(_lightField.Subquery([pyObject](auto l) { return boost::python::call<PythonLightField>(pyObject, PythonLightField(l)).query(); }));
`&pyObject`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        return PythonLightField(_lightField.Subquery([pyObject](auto l) { return boost::python::call<PythonLightField>(pyObject, PythonLightField(l)).query(); }));
`const auto &l`?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        std::vector<PythonLightField> pythonLightFields = std::vector<PythonLightField>(
`auto`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    PythonLightField Discretize(lightdb::Dimension dimension, double interval) {
`const`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    PythonLightField Map(PyObject *udf, std::string path) {
`const std::string &path` (can we not use std::filesystem::path?)

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        auto yolo = lightdb::extensibility::Load("yolo", path);
Hardcoded UDF

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        return PythonLightField(_lightField.Save(static_cast<std::filesystem::path>(fileName)));
Use implicit conversion

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    lightdb::LightFieldReference query() {
const member?  Not sure.

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +class ExternalEntry {
Move catalog stuff to catalog file

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    ExternalEntry(const std::filesystem::path &filename, std::map<std::string, std::string> options)
const ref options

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +          _options(options)
... or std::move(options)?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    std::filesystem::path _filename;
const

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    std::map<std::string, std::string> _options;
const

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +static PythonLightField Load(const std::string &filepath, boost::python::dict mydict) {
mydict can be a const ref

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +static PythonLightField Load(const std::string &filepath, boost::python::dict mydict) {
Rename mydict to reflect its semantics (e.g., just `options`)

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    lightdb::GeometryReference geometry = lightdb::GeometryReference::make<lightdb::EquirectangularGeometry>(lightdb::EquirectangularGeometry::Samples());
auto

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    std::map<std::string, std::string> myMap;
`myMap` -> `string_options`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    for (int i = 0; i < len(keys); ++i) {
Range-based loop

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +                std::cout<<"Key invalid, map might be incomplete"<<std::endl;
All instances are convertible to strings in Python; why would this fail?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        boost::python::extract<std::string> extractor_keys(keys[i]);
Move dict->string map to a separate `utilities.h` helper file

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    ExternalEntry entry = ExternalEntry(filepath, myMap);
`ExternalEntry entry(filepath, myMap);`

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    return PythonLightField(lightdb::logical::Load(filepath, lightdb::Volume::angular(), geometry));
Hardcoded `angular()`?  (What is `angular()` anyway?)

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    // return PythonLightField(lightdb::logical::Load(filepath, myMap));
Dead code

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +// typedef std::map<std::string, boost::any> mymap_t;
Dead code

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +class OptimizerWrapper : public lightdb::optimization::Optimizer, public boost::python::wrapper<lightdb::optimization::Optimizer> {
Can you just use an anonymous class here?  Not sure.

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    boost::python::def("SetUpLocalEnvironment", SetUpLocalEnvironment);
What is the purpose of this function?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +            .def("Hevc", &lightdb::Codec::hevc, boost::python::return_value_policy<boost::python::reference_existing_object>())
Uppercase HEVC

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +            .def("Hevc", &lightdb::Codec::hevc, boost::python::return_value_policy<boost::python::reference_existing_object>())
Wait maybe not?  What does PEP say?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    // boost::python::class_<lightdb::Point2D>("Point2D", boost::python::init<double, double>());
Dead code?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +#include <boost/python.hpp>
Dependencies before local includes

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +namespace Python {
LightDB::Python

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +        Source(const int index, std::filesystem::path filename, lightdb::Codec codec, const lightdb::Configuration configuration, std::map<std::string, string> options)
refs or std::move

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +    class PySource {
PySource: public Source?  Not sure

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +        ExternalEntry(const std::filesystem::path &filename, std::map<std::string, std::string> options)
&options or std::move

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +        std::filesystem::path _filename;
const?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +        Catalog(std::filesystem::path &filename)
const or std::move

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Catalog.cc
> +        std::filesystem::path _filename;
const?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Dict2Map.hh
> +namespace bpy = boost::python;
No namespace aliases in headers :(

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Dict2Map.hh
> +    typedef std::map<key_t, val_t> map_t;
using

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Dict2Map.hh
> +    /// constructor
We know it's a constructor :)

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Dict2Map.hh
> +#ifdef BOOST_PYTHON_SUPPORTS_PY_SIGNATURES
Was this code copied from somewhere?  What is BOOST_PYTHON_SUPPORTS_PY_SIGNATURES?

2020-04-06 03:59 UTC, BrandonHaynes commented on python/src/Dict2Map.hh
> +struct Dict2Map {
What is the purpose of this class?

2020-04-08 15:48 UTC, mundrapranay commented on CMakeLists.txt
> +add_subdirectory(python EXCLUDE_FROM_ALL)
Yes

2020-05-07 22:45 UTC, BrandonHaynes reviewed
Don't check in `python/.CMakeLists.txt.swp`

2020-05-07 22:45 UTC, BrandonHaynes commented on CMakeLists.txt
> +message("Include dir: ${CMAKE_BINARY_DIR}/protobuf")
Remove logging (I might have added this)

2020-05-07 22:45 UTC, BrandonHaynes commented on cmake/Modules/FindFFmpeg.cmake
> +    message("Component libraries: ${${_component}_LIBRARIES}")
Remove logging

2020-05-07 22:45 UTC, BrandonHaynes commented on cmake/Modules/FindGPAC.cmake
> +  message("**found gpac")
x

2020-05-07 22:45 UTC, BrandonHaynes commented on cmake/Modules/FindGPAC.cmake
> +  set(GPAC_LIBRARIES "/usr/lib/x86_64-linux-gnu/libgpac.so")
No hardcoded paths

2020-05-07 22:45 UTC, BrandonHaynes commented on core/CMakeLists.txt
> +  if (subdir MATCHES "../python/src")
?

2020-05-07 22:45 UTC, BrandonHaynes commented on core/CMakeLists.txt
> +list(FILTER LIGHTDB_SOURCES EXCLUDE REGEX "../python/src")
?

2020-05-07 22:45 UTC, BrandonHaynes commented on core/execution/include/Environment.h
> +#include <iostream>
?

2020-05-07 22:45 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +        constexpr SpatiotemporalRange(const double start, const double end)
Why is this overload needed?  There is a version in the base class and an implicit conversion from double to number.

2020-05-07 22:45 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +            : internal::Range<ThetaRange, angle, internal::limits::theta>::Range(angle(start), angle(end))
Same as above

2020-05-07 22:45 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +        constexpr PhiRange(const double start, const double end)
Same as above

2020-05-07 22:45 UTC, BrandonHaynes commented on core/model/include/Geometry.h
> +        static constexpr const Volume angular() { return {{0, 0}, {0, 0}, {0, 0}, {0, 0},
?

2020-05-07 22:45 UTC, BrandonHaynes commented on plugins/yolo/tmp/yolo-cfgcmd.txt
> +cmd='/usr/local/bin/cmake;-DCMAKE_BUILD_TYPE=debug;-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>;-DLIGHTDB_INCLUDES:list=/home/pranay99/lightdb/thirdparty/NvEnc/inc|/usr/local/cuda-9.0/include|/usr/inclu
?

2020-05-07 22:45 UTC, BrandonHaynes commented on plugins/yolo/tmp/yolo-cfgcmd.txt.in
> +cmd='@cmd@'
?

2020-05-07 22:45 UTC, BrandonHaynes commented on python/CMakeLists.txt
> +#set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/../cmake/Modules/")
Remove dead code if not needed

2020-05-07 22:45 UTC, BrandonHaynes commented on python/CMakeLists.txt
> +set(ALGEBRA_SOURCES "src/Algebra_ext.cc")
Don't hardcoded buildset

2020-05-07 22:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +class PythonLightField {
?

2020-05-07 22:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +    boost::python::def("SetUpLocalEnvironment", SetUpLocalEnvironment);
?

2020-05-07 22:45 UTC, BrandonHaynes commented on core/utility/include/options.h
> +    private:
This class shouldn't both derive from undered_map and contain an internal instance of one.  Remove the private field and delegate to the base constructor.

2020-05-07 22:45 UTC, BrandonHaynes commented on plugins/blur/tmp/blur-cfgcmd.txt
> +cmd='/usr/local/bin/cmake;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>;-DLIGHTDB_INCLUDES:list=/home/pranay99/lightdb/thirdparty/NvEnc/inc|/usr/local/cuda-9.0/include|/usr/inc
Don't check in `tmp` directories.

2020-05-07 22:45 UTC, BrandonHaynes commented on plugins/yolo/tmp/yolo-cfgcmd.txt
> +cmd='/usr/local/bin/cmake;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>;-DLIGHTDB_INCLUDES:list=/home/pranay99/lightdb/thirdparty/NvEnc/inc|/usr/local/cuda-9.0/include|/usr/inc
Same

2020-05-14 17:45 UTC, BrandonHaynes requested changes

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +typedef lightdb::number angle;
`using`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +typedef lightdb::number angle;
(Can't do either inside a header file though)

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +class MeshGeometryWrapper : public lightdb::MeshGeometry, public boost::python::wrapper<lightdb::MeshGeometry> {
Move all to `PythonGeometry.h`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +        double u(angle theth, angle phi) const {
theta

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +//#pragma GCC visibility push(default)
Remove both pragmas

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +namespace Python {
namespace lightdb::python

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +        PythonOptions(const boost::python::dict optDict) {
ref

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +            boost::python::list keys = boost::python::list(optDict.keys());
auto

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +            for (int i = 0; i < len(keys); ++i) {
Does boost::python::list support iteration?  If so `for(auto key: keys)`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +                if (key.compare("Volume") == 0) {
Move into private static function

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/options.cc
> +        std::unordered_map<TKey, TValue> internalMap;
_internalMap

2020-05-14 17:45 UTC, BrandonHaynes commented on pythonTests/test.py
> +query = Load("/home/pranay99/lightdb/test/resources/test-pattern.h264", {"Volume":vol, "Projection":geo}).Save("/home/pranay99/test.mp4")
Remove hardcoded path

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
> +#include "options.cc"
This file should be named `PythonOptions.h`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
>  namespace Python {
lightdb::python

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
>          return PythonLightField(_lightField.Union(lightFields));
PythonLightField class should be in PythonLightField.h

2020-05-14 17:45 UTC, BrandonHaynes commented on python/CMakeLists.txt
>  set(ALGEBRA_SOURCES "src/Algebra_ext.cc")
Rename `Algebra_ext.cc` to something like "PyhthonAPI.cc"

2020-05-14 17:45 UTC, BrandonHaynes commented on python/CMakeLists.txt
>  set(ALGEBRA_SOURCES "src/Algebra_ext.cc")
Or maybe `Module.cc`?  And then move API to `Algebra.h`?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/Algebra_ext.cc
>  class OptimizerWrapper : public lightdb::optimization::Optimizer, public boost::python::wrapper<lightdb::optimization::Optimizer> {
Move to Optimizer.h

2020-05-14 17:45 UTC, BrandonHaynes commented on .gitignore
> +.yolo-cfgmd.txt.in
`.*-cfgmd.txt*`

2020-05-14 17:45 UTC, BrandonHaynes commented on core/utility/include/options.h
> +        options(const std::unordered_map<TKey, TValue> string_options)
const ref

2020-05-14 17:45 UTC, BrandonHaynes commented on core/utility/include/options.h
> +            auto value = this->find(key);
Isn't `this` superfluous?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +#define LIGHTDB_PYTHON_LIGHT_FIELD_H
\n

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +#include "Greyscale.h"
Superfluous?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/pyoptions.h
> +#define LIGHTDB_PYTHON_OPTIONS_H
\n

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +#include "pyoptions.h"
pyoptions.h after core includes

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +return PythonLightField(lightdb::logical::Load(filepath, opt.options()));
PythonOptions should have an implicit conversion to lightdb::options, not a member function.

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/pyoptions.h
> +namespace lightdb::python {
`key == "Volume"` (`Compare` is too broad)

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/pyoptions.h
> +namespace lightdb::python {
`optDict` should be a ref

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/pyoptions.h
> +namespace lightdb::python {
`for(auto key: optDict.keys())`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +        PythonLightField(const lightdb::LightFieldReference &lightField);
`explicit`

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +        PythonLightField Partition(lightdb::Dimension dimension, const double interval);
`const` is superfluous on an elementary parameter in a prototype; remove

2020-05-14 17:45 UTC, BrandonHaynes commented on python/include/PythonLightField.h
> +        PythonLightField Discretize(const lightdb::Dimension dimension, double interval);
Remove `const` as above

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/PythonLightField.cc
> +    PythonLightField PythonLightField::SelectPhi(const lightdb::PhiRange &phiRange) {
Are you not using overloads for some reason?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +namespace lightdb::python {
Why is SetUpLocalEnvironment needed?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +PythonOptions opt(string_options);
Indent

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +PythonOptions opt(string_options);
Use implicit conversion

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +#include "PythonLightField.h"
Rename `pymain.cc` to `Module.cc`

2020-05-14 17:45 UTC, BrandonHaynes commented on .gitignore
> +.yolo-cfgmd.txt.in
Also `.CMakeLists.txt.swp` seems to be checked in?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/PythonLightField.cc
> +        auto yolo = lightdb::extensibility::Load("yolo", path);
Add a `//TODO` comment here since this is unfinished

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +namespace lightdb::python {
What is the definition of `ExecuteLightField` (and ExecuteLightFieldAndOptimizer) needed for?  Wouldn't `static_cast`s be sufficient?

2020-05-14 17:45 UTC, BrandonHaynes commented on python/src/pymain.cc
> +#include "PythonLightField.h"
Remove superfluous `this` indirections.
Remove typedefs.
Fix spelling of `theth` to `theta`
Remove `SetupLocalEnvironment` or add TODO
Remove pragmas

2020-05-18 19:07 UTC, BrandonHaynes commented
Add Python API

2020-05-18 19:07 UTC, merged